/*
SPDX-FileCopyrightText: 2026 Humdek, University of Bern
SPDX-License-Identifier: MPL-2.0
*/
/**
 * GENERATED BY scripts/plugins-sync.mjs — DO NOT EDIT BY HAND.
 * Profile: web-preview
 * Generated at: 2026-06-24T22:30:33.180Z
 *
 * Mobile plugin style impls. Re-run `npm run plugins:sync -- <profile>` to update.
 */

import type { TPluginStyleImplMap } from '@/components/renderer/types';

import { registerMobile as plugin0 } from '@selfhelp/sh2-shp-survey-js-mobile';

const registrations = [
    plugin0(),
];

function buildStyleImpls(): TPluginStyleImplMap {
    const map: TPluginStyleImplMap = {};
    for (const registration of registrations) {
        if (!registration || !registration.styles) continue;
        for (const style of registration.styles) {
            map[style.name] = style.component as unknown as TPluginStyleImplMap[string];
        }
    }
    return map;
}

function buildOwners(): Record<string, string> {
    const map: Record<string, string> = {};
    for (const registration of registrations) {
        if (!registration || !registration.styles) continue;
        for (const style of registration.styles) {
            map[style.name] = registration.id;
        }
    }
    return map;
}

export const registeredPluginStyleImpls: TPluginStyleImplMap = buildStyleImpls();
export const registeredPluginStyleOwners: Record<string, string> = buildOwners();

export const registeredPluginVersions: Record<string, string> = {
    "sh2-shp-survey-js": "0.3.3",
};
